services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_CREATE_DROP: ${POSTGRES_CREATE_DROP}
      SECRET_KEY: ${SECRET_KEY}
      JWT_EXPIRATION_TIME: ${JWT_EXPIRATION_TIME}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      SWAGGER_ENABLED: ${SWAGGER_ENABLED}
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
